name: Android CI

on:
  push:
      paths-ignore:
          - '**/README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Unit test with Gradle
#        run: ./gradlew testDebugUnitTest
#
#  gen-api-latest:
#    runs-on: ubuntu-latest
#    needs:
#      - build
#    outputs:
#      api: ${{ steps.api.outputs.list }}
#    steps:
#      - run: |
#          ruby -e 'puts "list=#{(29..33).to_a.to_s}"' >> $GITHUB_OUTPUT
#        id: api
#
#  device-test-latest:
#    runs-on: macos-latest
#    needs: gen-api-latest
#    strategy:
#      matrix:
#        api-level: ${{ fromJson(needs.gen-api-latest.outputs.api) }}
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Device test with Gradle
#        uses: ReactiveCircus/android-emulator-runner@v2
#        with:
#          api-level: ${{matrix.api-level}}
#          target: google_apis
#          arch: x86_64
#          script: ./gradlew connectedCheck
  release:
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: release
      cancel-in-progress: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN}}
        run: |
          npm install
          npx semantic-release
      - name: Generate app Bundle.
        run: ./gradlew app:bundleRelease --stacktrace
      - uses: ilharp/sign-android-release@v1
        name: Sign app Bundle
        # ID used to access action output
        id: sign_app
        with:
          releaseDir: app/build/outputs/bundle/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 33.0.0
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: signed_app_bundle
          path: app/build/outputs/bundle/release/app-release.aab
